language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "8"
script:
  - npm run validate
after_success:
  - npm run report-coverage
# use a bash script to determine
# if we are at master when running semantic-release
#- npm run semantic-release
branches:
  only:
    - master
    - develop
    - /^greenkeeper\/.*$/
